## Service
apiVersion: v1
kind: Service
metadata:
  name: dev-remi-sys-app
  labels:
    app: dev-remi-sys-app
spec:
  type: NodePort
  ports:
    - name: dev-remi-sys-app
      port: 1020
      protocol: TCP
      targetPort: 1020
      nodePort: 30020
  selector:
    app: dev-remi-sys-app
---
## Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-remi-sys-app
  labels:
    app: dev-remi-sys-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-remi-sys-app
  template:
    metadata:
      labels:
        app: dev-remi-sys-app
    spec:
      containers:
      - image: harbor.******.com/remi-top/dev-remi-sys-app
        imagePullPolicy: Always
        name: dev-remi-sys-app
        ports:
        - containerPort: 1020
          protocol: TCP
        env:
        - name: NACOS_HOST
          value: 192.168.31.200
        - name: NACOS_PORT
          value: "30888"
        - name: NAME_SPACE
          value: dev
        - name: GROUP_NAME
          value: dev
        - name: spring.application.name
          value: remi-sys-web
        - name: spring.profiles.active
          value: dev
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.2"
            memory: "200Mi"
        volumeMounts:
        - name: logs
          mountPath: /logs
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: remi-log