# 服务端口号
server:
  port: 8080
  # tomcat 配置
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 500
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  application:
    name: remi-boot-web
  profiles:
    active: ${cfg.env}
  # 循环依赖的问题
  main:
    allow-circular-references: true
  # MVC默认的路径匹配策略为PATH_PATTERN_PARSER，需要修改为ANT_PATH_MATCHER 解决swagger兼容性问题
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# mybatis-plus
mybatis-plus:
  configuration:
    #控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mapper映射文件路径
  mapper-locations: classpath*:/*-infra/src/main/resources/mapper/*.xml, classpath*:/mapper/**.xml

#pagehelper
pagehelper:
  # helper-dialect: mysql
  #分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。 你可以配置helperDialect 属性来指定分页插件使用哪种方言。
  auto-runtime-dialect: true
  #分页合理化参数，默认值为 false 。当该参数设置为 true 时， pageNum<=0 时会查询第一页， pageNum>pages （超过总数时），会查询最后一页。
  reasonable: true
  #支持通过Mapper接口参数传递page参数,默认值为false
  support-methods-arguments: true
  #默认值为 false ，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit =0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）。
  page-size-zero: true
  #为了支持 startPage(Object params) 方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  params: count=countSql

# feign
feign:
  okhttp:
    enabled: true
  hystrix:
    enabled: true
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000

# springdoc
springdoc:
  group-configs:
    - group: web
      packages-to-scan: ai.remi.boot.web
    - group: app
      packages-to-scan: ai.remi.boot.app

# 定义日志输出级别
logging:
  level:
    com.startdis: debug
    # spring 包日志输出级别
    org.springframework: info
    # alibaba 包日志输出级别
    com.alibaba.cloud: info
    # nacos 心跳 INFO 屏蔽
    com.alibaba.nacos: off
    # mybatis-plus
    com.baomidou.mybatisplus: debug